name: checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  checks:
    strategy:
      matrix:
        script: [lint, test, typecheck]
    name: ${{ matrix.script }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
      - run: npm i -g pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run ${{ matrix.script }}
